### ISSUE TITLE
update_side_menu

### ISSUE THREAD

**Issue by Anno328** [hurikake06/pet#102]
**問題・課題点**
ヘッダーの使い勝手が悪い。

**改善案**
ヘッダー要素の一部をサイドメニューへ移行する。

**Comment by hurikake06** [comment]
ヘッダー・サイドメニューに
それぞれどういう機能を持たせるか、
一度スクラップボックスでまとめてから移行たほうがいいと思う。

提案：
ヘッダーはユーザモードによって切り替えているが、
サイドメニューにモードに依存しない部分をまとめては？
