### ISSUE TITLE
css_refactoring

### ISSUE THREAD

**Issue by hurikake06** [hurikake06/pet#112]
**問題・課題点**
cssの整理、scssへ移行

**改善案**

- [x] application.scss & cg/layouts.scss　の整理
- [x] viewに直接記載してあるcssをスタイルシートへ移行

**Comment by KituneUdon** [comment]
shares/user/_list.html.erb、shares/host/_list.html.erb、shares/_new_form.html.erbの移行は#196 でやっています

**Comment by KituneUdon** [comment]
それ以外のviewのcssの移行は終わったのでこれでこのissueを閉じます
