### ISSUE TITLE
update_edit_user_page

### ISSUE THREAD

**Issue by Anno328** [hurikake06/pet#167]
**問題・課題点**
ユーザ編集画面の要素が不十分、レイアウトが見づらい

**改善案**
ユーザ編集画面に要素追加、レイアウト改善

**必要機能**
- [ ] プロフィール写真変更
- [x] 名前変更
- [x] About編集

**Comment by negi0109** [comment]
nameやaboutなど、プロフィール設定用のページを想定しているように見えますが、
姓名、年齢、住所などの個人情報などの入力はどうしますか？？

**Comment by Anno328** [comment]
個人情報などの入力は同一フォーム内で、プロフィール情報とは区別させて表示したいです。

**Comment by negi0109** [comment]
フォーム内にissueの情報又、編集を追加しました。
プロフィール写真変更は、
フォームに含めない形で実装するため、後に行います。
