### ISSUE TITLE
update_search_page

### ISSUE THREAD

**Issue by negi0109** [hurikake06/pet#171]
**問題・課題点**
#134 時点では課題に上がらなかったため別のissueとしてあげました。

- [x] 検索結果が一つもない際の画面
- [x] 検索キーワードが未入力な際の画面

がないため修正・調整をお願いします。

**既に行ったこと**
#134 で、検索キーワードの未入力・入力状態を保存するために、
変数`@searched`を用意し、簡単な適用のみしました。

**Comment by negi0109** [comment]
検索結果画面をajaxみたいなものに対応させました。
作業既に行える状態です。わからないことがあれば @negi0109 にお願いします。

**Comment by KituneUdon** [comment]
Scrapboxに現在出ている問題点の解決案を出してみたのでどの案がいいのか意見をください。
ほかにこうしたほうがいいのでは？という意見もあったらScrapboxまたは、Githubでコメントをお願いします。
Scrapboxに意見を書いた場合は、Scrapboxに書いたということをコメントしていただけるとありがたいです。
[検索画面の問題点の解決案_メモ](https://scrapbox.io/SmartApp/%E6%A4%9C%E7%B4%A2%E7%94%BB%E9%9D%A2%E3%81%AE%E5%95%8F%E9%A1%8C%E7%82%B9%E3%81%AE%E8%A7%A3%E6%B1%BA%E6%A1%88_%E3%83%A1%E3%83%A2)
